<?php
/**
 * Add Icons Select List.
 *
 * @package ThinkUpThemes
 */


/* ----------------------------------------------------------------------------------
	Services - Add Icon Select List (makes main file look messy)
---------------------------------------------------------------------------------- */

function thinkup_builder_fontawesomeicons() {
global $icon_icon;

	echo '<option '; ?><?php if($icon_icon == "adjust") { echo "selected"; } ?><?php echo ' value="adjust">Adjust</option>
		<option '; ?><?php if($icon_icon == "adn") { echo "selected"; } ?><?php echo ' value="adn">Adn</option>
		<option '; ?><?php if($icon_icon == "align-center") { echo "selected"; } ?><?php echo ' value="align-center">Align-Center</option>
		<option '; ?><?php if($icon_icon == "align-justify") { echo "selected"; } ?><?php echo ' value="align-justify">Align-Justify</option>
		<option '; ?><?php if($icon_icon == "align-left") { echo "selected"; } ?><?php echo ' value="align-left">Align-Left</option>
		<option '; ?><?php if($icon_icon == "align-right") { echo "selected"; } ?><?php echo ' value="align-right">Align-Right</option>
		<option '; ?><?php if($icon_icon == "ambulance") { echo "selected"; } ?><?php echo ' value="ambulance">Ambulance</option>
		<option '; ?><?php if($icon_icon == "anchor") { echo "selected"; } ?><?php echo ' value="anchor">Anchor</option>
		<option '; ?><?php if($icon_icon == "android") { echo "selected"; } ?><?php echo ' value="android">Android</option>
		<option '; ?><?php if($icon_icon == "angellist") { echo "selected"; } ?><?php echo ' value="angellist">Angellist</option>
		<option '; ?><?php if($icon_icon == "angle-double-down") { echo "selected"; } ?><?php echo ' value="angle-double-down">Angle-Double-Down</option>
		<option '; ?><?php if($icon_icon == "angle-double-left") { echo "selected"; } ?><?php echo ' value="angle-double-left">Angle-Double-Left</option>
		<option '; ?><?php if($icon_icon == "angle-double-right") { echo "selected"; } ?><?php echo ' value="angle-double-right">Angle-Double-Right</option>
		<option '; ?><?php if($icon_icon == "angle-double-up") { echo "selected"; } ?><?php echo ' value="angle-double-up">Angle-Double-Up</option>
		<option '; ?><?php if($icon_icon == "angle-down") { echo "selected"; } ?><?php echo ' value="angle-down">Angle-Down</option>
		<option '; ?><?php if($icon_icon == "angle-left") { echo "selected"; } ?><?php echo ' value="angle-left">Angle-Left</option>
		<option '; ?><?php if($icon_icon == "angle-right") { echo "selected"; } ?><?php echo ' value="angle-right">Angle-Right</option>
		<option '; ?><?php if($icon_icon == "angle-up") { echo "selected"; } ?><?php echo ' value="angle-up">Angle-Up</option>
		<option '; ?><?php if($icon_icon == "apple") { echo "selected"; } ?><?php echo ' value="apple">Apple</option>
		<option '; ?><?php if($icon_icon == "archive") { echo "selected"; } ?><?php echo ' value="archive">Archive</option>
		<option '; ?><?php if($icon_icon == "area-chart") { echo "selected"; } ?><?php echo ' value="area-chart">Area-Chart</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-down") { echo "selected"; } ?><?php echo ' value="arrow-circle-down">Arrow-Circle-Down</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-left") { echo "selected"; } ?><?php echo ' value="arrow-circle-left">Arrow-Circle-Left</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-o-down") { echo "selected"; } ?><?php echo ' value="arrow-circle-o-down">Arrow-Circle-O-Down</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-o-left") { echo "selected"; } ?><?php echo ' value="arrow-circle-o-left">Arrow-Circle-O-Left</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-o-right") { echo "selected"; } ?><?php echo ' value="arrow-circle-o-right">Arrow-Circle-O-Right</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-o-up") { echo "selected"; } ?><?php echo ' value="arrow-circle-o-up">Arrow-Circle-O-Up</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-right") { echo "selected"; } ?><?php echo ' value="arrow-circle-right">Arrow-Circle-Right</option>
		<option '; ?><?php if($icon_icon == "arrow-circle-up") { echo "selected"; } ?><?php echo ' value="arrow-circle-up">Arrow-Circle-Up</option>
		<option '; ?><?php if($icon_icon == "arrow-down") { echo "selected"; } ?><?php echo ' value="arrow-down">Arrow-Down</option>
		<option '; ?><?php if($icon_icon == "arrow-left") { echo "selected"; } ?><?php echo ' value="arrow-left">Arrow-Left</option>
		<option '; ?><?php if($icon_icon == "arrow-right") { echo "selected"; } ?><?php echo ' value="arrow-right">Arrow-Right</option>
		<option '; ?><?php if($icon_icon == "arrows") { echo "selected"; } ?><?php echo ' value="arrows">Arrows</option>
		<option '; ?><?php if($icon_icon == "arrows-alt") { echo "selected"; } ?><?php echo ' value="arrows-alt">Arrows-Alt</option>
		<option '; ?><?php if($icon_icon == "arrows-h") { echo "selected"; } ?><?php echo ' value="arrows-h">Arrows-H</option>
		<option '; ?><?php if($icon_icon == "arrows-v") { echo "selected"; } ?><?php echo ' value="arrows-v">Arrows-V</option>
		<option '; ?><?php if($icon_icon == "arrow-up") { echo "selected"; } ?><?php echo ' value="arrow-up">Arrow-Up</option>
		<option '; ?><?php if($icon_icon == "asterisk") { echo "selected"; } ?><?php echo ' value="asterisk">Asterisk</option>
		<option '; ?><?php if($icon_icon == "at") { echo "selected"; } ?><?php echo ' value="at">At</option>
		<option '; ?><?php if($icon_icon == "automobile") { echo "selected"; } ?><?php echo ' value="automobile">Automobile</option>
		<option '; ?><?php if($icon_icon == "backward") { echo "selected"; } ?><?php echo ' value="backward">Backward</option>
		<option '; ?><?php if($icon_icon == "ban") { echo "selected"; } ?><?php echo ' value="ban">Ban</option>
		<option '; ?><?php if($icon_icon == "bank") { echo "selected"; } ?><?php echo ' value="bank">Bank</option>
		<option '; ?><?php if($icon_icon == "bar-chart") { echo "selected"; } ?><?php echo ' value="bar-chart">Bar-Chart</option>
		<option '; ?><?php if($icon_icon == "bar-chart-o") { echo "selected"; } ?><?php echo ' value="bar-chart-o">Bar-Chart-O</option>
		<option '; ?><?php if($icon_icon == "barcode") { echo "selected"; } ?><?php echo ' value="barcode">Barcode</option>
		<option '; ?><?php if($icon_icon == "bars") { echo "selected"; } ?><?php echo ' value="bars">Bars</option>
		<option '; ?><?php if($icon_icon == "beer") { echo "selected"; } ?><?php echo ' value="beer">Beer</option>
		<option '; ?><?php if($icon_icon == "behance") { echo "selected"; } ?><?php echo ' value="behance">Behance</option>
		<option '; ?><?php if($icon_icon == "behance-square") { echo "selected"; } ?><?php echo ' value="behance-square">Behance-Square</option>
		<option '; ?><?php if($icon_icon == "bell") { echo "selected"; } ?><?php echo ' value="bell">Bell</option>
		<option '; ?><?php if($icon_icon == "bell-o") { echo "selected"; } ?><?php echo ' value="bell-o">Bell-O</option>
		<option '; ?><?php if($icon_icon == "bell-slash") { echo "selected"; } ?><?php echo ' value="bell-slash">Bell-Slash</option>
		<option '; ?><?php if($icon_icon == "bell-slash-o") { echo "selected"; } ?><?php echo ' value="bell-slash-o">Bell-Slash-O</option>
		<option '; ?><?php if($icon_icon == "bicycle") { echo "selected"; } ?><?php echo ' value="bicycle">Bicycle</option>
		<option '; ?><?php if($icon_icon == "binoculars") { echo "selected"; } ?><?php echo ' value="binoculars">Binoculars</option>
		<option '; ?><?php if($icon_icon == "birthday-cake") { echo "selected"; } ?><?php echo ' value="birthday-cake">Birthday-Cake</option>
		<option '; ?><?php if($icon_icon == "bitbucket") { echo "selected"; } ?><?php echo ' value="bitbucket">Bitbucket</option>
		<option '; ?><?php if($icon_icon == "bitbucket-square") { echo "selected"; } ?><?php echo ' value="bitbucket-square">Bitbucket-Square</option>
		<option '; ?><?php if($icon_icon == "bitcoin") { echo "selected"; } ?><?php echo ' value="bitcoin">Bitcoin</option>
		<option '; ?><?php if($icon_icon == "bold") { echo "selected"; } ?><?php echo ' value="bold">Bold</option>
		<option '; ?><?php if($icon_icon == "bolt") { echo "selected"; } ?><?php echo ' value="bolt">Bolt</option>
		<option '; ?><?php if($icon_icon == "bomb") { echo "selected"; } ?><?php echo ' value="bomb">Bomb</option>
		<option '; ?><?php if($icon_icon == "book") { echo "selected"; } ?><?php echo ' value="book">Book</option>
		<option '; ?><?php if($icon_icon == "bookmark") { echo "selected"; } ?><?php echo ' value="bookmark">Bookmark</option>
		<option '; ?><?php if($icon_icon == "bookmark-o") { echo "selected"; } ?><?php echo ' value="bookmark-o">Bookmark-O</option>
		<option '; ?><?php if($icon_icon == "briefcase") { echo "selected"; } ?><?php echo ' value="briefcase">Briefcase</option>
		<option '; ?><?php if($icon_icon == "btc") { echo "selected"; } ?><?php echo ' value="btc">Btc</option>
		<option '; ?><?php if($icon_icon == "bug") { echo "selected"; } ?><?php echo ' value="bug">Bug</option>
		<option '; ?><?php if($icon_icon == "building") { echo "selected"; } ?><?php echo ' value="building">Building</option>
		<option '; ?><?php if($icon_icon == "building-o") { echo "selected"; } ?><?php echo ' value="building-o">Building-O</option>
		<option '; ?><?php if($icon_icon == "bullhorn") { echo "selected"; } ?><?php echo ' value="bullhorn">Bullhorn</option>
		<option '; ?><?php if($icon_icon == "bullseye") { echo "selected"; } ?><?php echo ' value="bullseye">Bullseye</option>
		<option '; ?><?php if($icon_icon == "bus") { echo "selected"; } ?><?php echo ' value="bus">Bus</option>
		<option '; ?><?php if($icon_icon == "cab") { echo "selected"; } ?><?php echo ' value="cab">Cab</option>
		<option '; ?><?php if($icon_icon == "calculator") { echo "selected"; } ?><?php echo ' value="calculator">Calculator</option>
		<option '; ?><?php if($icon_icon == "calendar") { echo "selected"; } ?><?php echo ' value="calendar">Calendar</option>
		<option '; ?><?php if($icon_icon == "calendar-o") { echo "selected"; } ?><?php echo ' value="calendar-o">Calendar-O</option>
		<option '; ?><?php if($icon_icon == "camera") { echo "selected"; } ?><?php echo ' value="camera">Camera</option>
		<option '; ?><?php if($icon_icon == "camera-retro") { echo "selected"; } ?><?php echo ' value="camera-retro">Camera-Retro</option>
		<option '; ?><?php if($icon_icon == "car") { echo "selected"; } ?><?php echo ' value="car">Car</option>
		<option '; ?><?php if($icon_icon == "caret-down") { echo "selected"; } ?><?php echo ' value="caret-down">Caret-Down</option>
		<option '; ?><?php if($icon_icon == "caret-left") { echo "selected"; } ?><?php echo ' value="caret-left">Caret-Left</option>
		<option '; ?><?php if($icon_icon == "caret-right") { echo "selected"; } ?><?php echo ' value="caret-right">Caret-Right</option>
		<option '; ?><?php if($icon_icon == "caret-square-o-down") { echo "selected"; } ?><?php echo ' value="caret-square-o-down">Caret-Square-O-Down</option>
		<option '; ?><?php if($icon_icon == "caret-square-o-left") { echo "selected"; } ?><?php echo ' value="caret-square-o-left">Caret-Square-O-Left</option>
		<option '; ?><?php if($icon_icon == "caret-square-o-right") { echo "selected"; } ?><?php echo ' value="caret-square-o-right">Caret-Square-O-Right</option>
		<option '; ?><?php if($icon_icon == "caret-square-o-up") { echo "selected"; } ?><?php echo ' value="caret-square-o-up">Caret-Square-O-Up</option>
		<option '; ?><?php if($icon_icon == "caret-up") { echo "selected"; } ?><?php echo ' value="caret-up">Caret-Up</option>
		<option '; ?><?php if($icon_icon == "cc") { echo "selected"; } ?><?php echo ' value="cc">Cc</option>
		<option '; ?><?php if($icon_icon == "cc-amex") { echo "selected"; } ?><?php echo ' value="cc-amex">Cc-Amex</option>
		<option '; ?><?php if($icon_icon == "cc-discover") { echo "selected"; } ?><?php echo ' value="cc-discover">Cc-Discover</option>
		<option '; ?><?php if($icon_icon == "cc-mastercard") { echo "selected"; } ?><?php echo ' value="cc-mastercard">Cc-Mastercard</option>
		<option '; ?><?php if($icon_icon == "cc-paypal") { echo "selected"; } ?><?php echo ' value="cc-paypal">Cc-Paypal</option>
		<option '; ?><?php if($icon_icon == "cc-stripe") { echo "selected"; } ?><?php echo ' value="cc-stripe">Cc-Stripe</option>
		<option '; ?><?php if($icon_icon == "cc-visa") { echo "selected"; } ?><?php echo ' value="cc-visa">Cc-Visa</option>
		<option '; ?><?php if($icon_icon == "certificate") { echo "selected"; } ?><?php echo ' value="certificate">Certificate</option>
		<option '; ?><?php if($icon_icon == "chain") { echo "selected"; } ?><?php echo ' value="chain">Chain</option>
		<option '; ?><?php if($icon_icon == "chain-broken") { echo "selected"; } ?><?php echo ' value="chain-broken">Chain-Broken</option>
		<option '; ?><?php if($icon_icon == "check") { echo "selected"; } ?><?php echo ' value="check">Check</option>
		<option '; ?><?php if($icon_icon == "check-circle") { echo "selected"; } ?><?php echo ' value="check-circle">Check-Circle</option>
		<option '; ?><?php if($icon_icon == "check-circle-o") { echo "selected"; } ?><?php echo ' value="check-circle-o">Check-Circle-O</option>
		<option '; ?><?php if($icon_icon == "check-square") { echo "selected"; } ?><?php echo ' value="check-square">Check-Square</option>
		<option '; ?><?php if($icon_icon == "check-square-o") { echo "selected"; } ?><?php echo ' value="check-square-o">Check-Square-O</option>
		<option '; ?><?php if($icon_icon == "chevron-circle-down") { echo "selected"; } ?><?php echo ' value="chevron-circle-down">Chevron-Circle-Down</option>
		<option '; ?><?php if($icon_icon == "chevron-circle-left") { echo "selected"; } ?><?php echo ' value="chevron-circle-left">Chevron-Circle-Left</option>
		<option '; ?><?php if($icon_icon == "chevron-circle-right") { echo "selected"; } ?><?php echo ' value="chevron-circle-right">Chevron-Circle-Right</option>
		<option '; ?><?php if($icon_icon == "chevron-circle-up") { echo "selected"; } ?><?php echo ' value="chevron-circle-up">Chevron-Circle-Up</option>
		<option '; ?><?php if($icon_icon == "chevron-down") { echo "selected"; } ?><?php echo ' value="chevron-down">Chevron-Down</option>
		<option '; ?><?php if($icon_icon == "chevron-left") { echo "selected"; } ?><?php echo ' value="chevron-left">Chevron-Left</option>
		<option '; ?><?php if($icon_icon == "chevron-right") { echo "selected"; } ?><?php echo ' value="chevron-right">Chevron-Right</option>
		<option '; ?><?php if($icon_icon == "chevron-up") { echo "selected"; } ?><?php echo ' value="chevron-up">Chevron-Up</option>
		<option '; ?><?php if($icon_icon == "child") { echo "selected"; } ?><?php echo ' value="child">Child</option>
		<option '; ?><?php if($icon_icon == "circle") { echo "selected"; } ?><?php echo ' value="circle">Circle</option>
		<option '; ?><?php if($icon_icon == "circle-o") { echo "selected"; } ?><?php echo ' value="circle-o">Circle-O</option>
		<option '; ?><?php if($icon_icon == "circle-o-notch") { echo "selected"; } ?><?php echo ' value="circle-o-notch">Circle-O-Notch</option>
		<option '; ?><?php if($icon_icon == "circle-thin") { echo "selected"; } ?><?php echo ' value="circle-thin">Circle-Thin</option>
		<option '; ?><?php if($icon_icon == "clipboard") { echo "selected"; } ?><?php echo ' value="clipboard">Clipboard</option>
		<option '; ?><?php if($icon_icon == "clock-o") { echo "selected"; } ?><?php echo ' value="clock-o">Clock-O</option>
		<option '; ?><?php if($icon_icon == "close") { echo "selected"; } ?><?php echo ' value="close">Close</option>
		<option '; ?><?php if($icon_icon == "cloud") { echo "selected"; } ?><?php echo ' value="cloud">Cloud</option>
		<option '; ?><?php if($icon_icon == "cloud-download") { echo "selected"; } ?><?php echo ' value="cloud-download">Cloud-Download</option>
		<option '; ?><?php if($icon_icon == "cloud-upload") { echo "selected"; } ?><?php echo ' value="cloud-upload">Cloud-Upload</option>
		<option '; ?><?php if($icon_icon == "cny") { echo "selected"; } ?><?php echo ' value="cny">Cny</option>
		<option '; ?><?php if($icon_icon == "code") { echo "selected"; } ?><?php echo ' value="code">Code</option>
		<option '; ?><?php if($icon_icon == "code-fork") { echo "selected"; } ?><?php echo ' value="code-fork">Code-Fork</option>
		<option '; ?><?php if($icon_icon == "codepen") { echo "selected"; } ?><?php echo ' value="codepen">Codepen</option>
		<option '; ?><?php if($icon_icon == "coffee") { echo "selected"; } ?><?php echo ' value="coffee">Coffee</option>
		<option '; ?><?php if($icon_icon == "cog") { echo "selected"; } ?><?php echo ' value="cog">Cog</option>
		<option '; ?><?php if($icon_icon == "cogs") { echo "selected"; } ?><?php echo ' value="cogs">Cogs</option>
		<option '; ?><?php if($icon_icon == "columns") { echo "selected"; } ?><?php echo ' value="columns">Columns</option>
		<option '; ?><?php if($icon_icon == "comment") { echo "selected"; } ?><?php echo ' value="comment">Comment</option>
		<option '; ?><?php if($icon_icon == "comment-o") { echo "selected"; } ?><?php echo ' value="comment-o">Comment-O</option>
		<option '; ?><?php if($icon_icon == "comments") { echo "selected"; } ?><?php echo ' value="comments">Comments</option>
		<option '; ?><?php if($icon_icon == "comments-o") { echo "selected"; } ?><?php echo ' value="comments-o">Comments-O</option>
		<option '; ?><?php if($icon_icon == "compass") { echo "selected"; } ?><?php echo ' value="compass">Compass</option>
		<option '; ?><?php if($icon_icon == "compress") { echo "selected"; } ?><?php echo ' value="compress">Compress</option>
		<option '; ?><?php if($icon_icon == "copy") { echo "selected"; } ?><?php echo ' value="copy">Copy</option>
		<option '; ?><?php if($icon_icon == "copyright") { echo "selected"; } ?><?php echo ' value="copyright">Copyright</option>
		<option '; ?><?php if($icon_icon == "credit-card") { echo "selected"; } ?><?php echo ' value="credit-card">Credit-Card</option>
		<option '; ?><?php if($icon_icon == "crop") { echo "selected"; } ?><?php echo ' value="crop">Crop</option>
		<option '; ?><?php if($icon_icon == "crosshairs") { echo "selected"; } ?><?php echo ' value="crosshairs">Crosshairs</option>
		<option '; ?><?php if($icon_icon == "css3") { echo "selected"; } ?><?php echo ' value="css3">Css3</option>
		<option '; ?><?php if($icon_icon == "cube") { echo "selected"; } ?><?php echo ' value="cube">Cube</option>
		<option '; ?><?php if($icon_icon == "cubes") { echo "selected"; } ?><?php echo ' value="cubes">Cubes</option>
		<option '; ?><?php if($icon_icon == "cut") { echo "selected"; } ?><?php echo ' value="cut">Cut</option>
		<option '; ?><?php if($icon_icon == "cutlery") { echo "selected"; } ?><?php echo ' value="cutlery">Cutlery</option>
		<option '; ?><?php if($icon_icon == "dashboard") { echo "selected"; } ?><?php echo ' value="dashboard">Dashboard</option>
		<option '; ?><?php if($icon_icon == "database") { echo "selected"; } ?><?php echo ' value="database">Database</option>
		<option '; ?><?php if($icon_icon == "dedent") { echo "selected"; } ?><?php echo ' value="dedent">Dedent</option>
		<option '; ?><?php if($icon_icon == "delicious") { echo "selected"; } ?><?php echo ' value="delicious">Delicious</option>
		<option '; ?><?php if($icon_icon == "desktop") { echo "selected"; } ?><?php echo ' value="desktop">Desktop</option>
		<option '; ?><?php if($icon_icon == "deviantart") { echo "selected"; } ?><?php echo ' value="deviantart">Deviantart</option>
		<option '; ?><?php if($icon_icon == "digg") { echo "selected"; } ?><?php echo ' value="digg">Digg</option>
		<option '; ?><?php if($icon_icon == "dollar") { echo "selected"; } ?><?php echo ' value="dollar">Dollar</option>
		<option '; ?><?php if($icon_icon == "dot-circle-o") { echo "selected"; } ?><?php echo ' value="dot-circle-o">Dot-Circle-O</option>
		<option '; ?><?php if($icon_icon == "download") { echo "selected"; } ?><?php echo ' value="download">Download</option>
		<option '; ?><?php if($icon_icon == "dribbble") { echo "selected"; } ?><?php echo ' value="dribbble">Dribbble</option>
		<option '; ?><?php if($icon_icon == "dropbox") { echo "selected"; } ?><?php echo ' value="dropbox">Dropbox</option>
		<option '; ?><?php if($icon_icon == "drupal") { echo "selected"; } ?><?php echo ' value="drupal">Drupal</option>
		<option '; ?><?php if($icon_icon == "edit") { echo "selected"; } ?><?php echo ' value="edit">Edit</option>
		<option '; ?><?php if($icon_icon == "eject") { echo "selected"; } ?><?php echo ' value="eject">Eject</option>
		<option '; ?><?php if($icon_icon == "ellipsis-h") { echo "selected"; } ?><?php echo ' value="ellipsis-h">Ellipsis-H</option>
		<option '; ?><?php if($icon_icon == "ellipsis-v") { echo "selected"; } ?><?php echo ' value="ellipsis-v">Ellipsis-V</option>
		<option '; ?><?php if($icon_icon == "empire") { echo "selected"; } ?><?php echo ' value="empire">Empire</option>
		<option '; ?><?php if($icon_icon == "envelope") { echo "selected"; } ?><?php echo ' value="envelope">Envelope</option>
		<option '; ?><?php if($icon_icon == "envelope-o") { echo "selected"; } ?><?php echo ' value="envelope-o">Envelope-O</option>
		<option '; ?><?php if($icon_icon == "envelope-square") { echo "selected"; } ?><?php echo ' value="envelope-square">Envelope-Square</option>
		<option '; ?><?php if($icon_icon == "eraser") { echo "selected"; } ?><?php echo ' value="eraser">Eraser</option>
		<option '; ?><?php if($icon_icon == "eur") { echo "selected"; } ?><?php echo ' value="eur">Eur</option>
		<option '; ?><?php if($icon_icon == "euro") { echo "selected"; } ?><?php echo ' value="euro">Euro</option>
		<option '; ?><?php if($icon_icon == "exchange") { echo "selected"; } ?><?php echo ' value="exchange">Exchange</option>
		<option '; ?><?php if($icon_icon == "exclamation") { echo "selected"; } ?><?php echo ' value="exclamation">Exclamation</option>
		<option '; ?><?php if($icon_icon == "exclamation-circle") { echo "selected"; } ?><?php echo ' value="exclamation-circle">Exclamation-Circle</option>
		<option '; ?><?php if($icon_icon == "exclamation-triangle") { echo "selected"; } ?><?php echo ' value="exclamation-triangle">Exclamation-Triangle</option>
		<option '; ?><?php if($icon_icon == "expand") { echo "selected"; } ?><?php echo ' value="expand">Expand</option>
		<option '; ?><?php if($icon_icon == "external-link") { echo "selected"; } ?><?php echo ' value="external-link">External-Link</option>
		<option '; ?><?php if($icon_icon == "external-link-square") { echo "selected"; } ?><?php echo ' value="external-link-square">External-Link-Square</option>
		<option '; ?><?php if($icon_icon == "eye") { echo "selected"; } ?><?php echo ' value="eye">Eye</option>
		<option '; ?><?php if($icon_icon == "eyedropper") { echo "selected"; } ?><?php echo ' value="eyedropper">Eyedropper</option>
		<option '; ?><?php if($icon_icon == "eye-slash") { echo "selected"; } ?><?php echo ' value="eye-slash">Eye-Slash</option>
		<option '; ?><?php if($icon_icon == "facebook") { echo "selected"; } ?><?php echo ' value="facebook">Facebook</option>
		<option '; ?><?php if($icon_icon == "facebook-square") { echo "selected"; } ?><?php echo ' value="facebook-square">Facebook-Square</option>
		<option '; ?><?php if($icon_icon == "fast-backward") { echo "selected"; } ?><?php echo ' value="fast-backward">Fast-Backward</option>
		<option '; ?><?php if($icon_icon == "fast-forward") { echo "selected"; } ?><?php echo ' value="fast-forward">Fast-Forward</option>
		<option '; ?><?php if($icon_icon == "fax") { echo "selected"; } ?><?php echo ' value="fax">Fax</option>
		<option '; ?><?php if($icon_icon == "female") { echo "selected"; } ?><?php echo ' value="female">Female</option>
		<option '; ?><?php if($icon_icon == "fighter-jet") { echo "selected"; } ?><?php echo ' value="fighter-jet">Fighter-Jet</option>
		<option '; ?><?php if($icon_icon == "file") { echo "selected"; } ?><?php echo ' value="file">File</option>
		<option '; ?><?php if($icon_icon == "file-archive-o") { echo "selected"; } ?><?php echo ' value="file-archive-o">File-Archive-O</option>
		<option '; ?><?php if($icon_icon == "file-audio-o") { echo "selected"; } ?><?php echo ' value="file-audio-o">File-Audio-O</option>
		<option '; ?><?php if($icon_icon == "file-code-o") { echo "selected"; } ?><?php echo ' value="file-code-o">File-Code-O</option>
		<option '; ?><?php if($icon_icon == "file-excel-o") { echo "selected"; } ?><?php echo ' value="file-excel-o">File-Excel-O</option>
		<option '; ?><?php if($icon_icon == "file-image-o") { echo "selected"; } ?><?php echo ' value="file-image-o">File-Image-O</option>
		<option '; ?><?php if($icon_icon == "file-movie-o") { echo "selected"; } ?><?php echo ' value="file-movie-o">File-Movie-O</option>
		<option '; ?><?php if($icon_icon == "file-o") { echo "selected"; } ?><?php echo ' value="file-o">File-O</option>
		<option '; ?><?php if($icon_icon == "file-pdf-o") { echo "selected"; } ?><?php echo ' value="file-pdf-o">File-Pdf-O</option>
		<option '; ?><?php if($icon_icon == "file-photo-o") { echo "selected"; } ?><?php echo ' value="file-photo-o">File-Photo-O</option>
		<option '; ?><?php if($icon_icon == "file-picture-o") { echo "selected"; } ?><?php echo ' value="file-picture-o">File-Picture-O</option>
		<option '; ?><?php if($icon_icon == "file-powerpoint-o") { echo "selected"; } ?><?php echo ' value="file-powerpoint-o">File-Powerpoint-O</option>
		<option '; ?><?php if($icon_icon == "files-o") { echo "selected"; } ?><?php echo ' value="files-o">Files-O</option>
		<option '; ?><?php if($icon_icon == "file-sound-o") { echo "selected"; } ?><?php echo ' value="file-sound-o">File-Sound-O</option>
		<option '; ?><?php if($icon_icon == "file-text") { echo "selected"; } ?><?php echo ' value="file-text">File-Text</option>
		<option '; ?><?php if($icon_icon == "file-text-o") { echo "selected"; } ?><?php echo ' value="file-text-o">File-Text-O</option>
		<option '; ?><?php if($icon_icon == "file-video-o") { echo "selected"; } ?><?php echo ' value="file-video-o">File-Video-O</option>
		<option '; ?><?php if($icon_icon == "file-word-o") { echo "selected"; } ?><?php echo ' value="file-word-o">File-Word-O</option>
		<option '; ?><?php if($icon_icon == "file-zip-o") { echo "selected"; } ?><?php echo ' value="file-zip-o">File-Zip-O</option>
		<option '; ?><?php if($icon_icon == "film") { echo "selected"; } ?><?php echo ' value="film">Film</option>
		<option '; ?><?php if($icon_icon == "filter") { echo "selected"; } ?><?php echo ' value="filter">Filter</option>
		<option '; ?><?php if($icon_icon == "fire") { echo "selected"; } ?><?php echo ' value="fire">Fire</option>
		<option '; ?><?php if($icon_icon == "fire-extinguisher") { echo "selected"; } ?><?php echo ' value="fire-extinguisher">Fire-Extinguisher</option>
		<option '; ?><?php if($icon_icon == "flag") { echo "selected"; } ?><?php echo ' value="flag">Flag</option>
		<option '; ?><?php if($icon_icon == "flag-checkered") { echo "selected"; } ?><?php echo ' value="flag-checkered">Flag-Checkered</option>
		<option '; ?><?php if($icon_icon == "flag-o") { echo "selected"; } ?><?php echo ' value="flag-o">Flag-O</option>
		<option '; ?><?php if($icon_icon == "flash") { echo "selected"; } ?><?php echo ' value="flash">Flash</option>
		<option '; ?><?php if($icon_icon == "flask") { echo "selected"; } ?><?php echo ' value="flask">Flask</option>
		<option '; ?><?php if($icon_icon == "flickr") { echo "selected"; } ?><?php echo ' value="flickr">Flickr</option>
		<option '; ?><?php if($icon_icon == "floppy-o") { echo "selected"; } ?><?php echo ' value="floppy-o">Floppy-O</option>
		<option '; ?><?php if($icon_icon == "folder") { echo "selected"; } ?><?php echo ' value="folder">Folder</option>
		<option '; ?><?php if($icon_icon == "folder-o") { echo "selected"; } ?><?php echo ' value="folder-o">Folder-O</option>
		<option '; ?><?php if($icon_icon == "folder-open") { echo "selected"; } ?><?php echo ' value="folder-open">Folder-Open</option>
		<option '; ?><?php if($icon_icon == "folder-open-o") { echo "selected"; } ?><?php echo ' value="folder-open-o">Folder-Open-O</option>
		<option '; ?><?php if($icon_icon == "font") { echo "selected"; } ?><?php echo ' value="font">Font</option>
		<option '; ?><?php if($icon_icon == "forward") { echo "selected"; } ?><?php echo ' value="forward">Forward</option>
		<option '; ?><?php if($icon_icon == "foursquare") { echo "selected"; } ?><?php echo ' value="foursquare">Foursquare</option>
		<option '; ?><?php if($icon_icon == "frown-o") { echo "selected"; } ?><?php echo ' value="frown-o">Frown-O</option>
		<option '; ?><?php if($icon_icon == "futbol-o") { echo "selected"; } ?><?php echo ' value="futbol-o">Futbol-O</option>
		<option '; ?><?php if($icon_icon == "gamepad") { echo "selected"; } ?><?php echo ' value="gamepad">Gamepad</option>
		<option '; ?><?php if($icon_icon == "gavel") { echo "selected"; } ?><?php echo ' value="gavel">Gavel</option>
		<option '; ?><?php if($icon_icon == "gbp") { echo "selected"; } ?><?php echo ' value="gbp">Gbp</option>
		<option '; ?><?php if($icon_icon == "ge") { echo "selected"; } ?><?php echo ' value="ge">Ge</option>
		<option '; ?><?php if($icon_icon == "gear") { echo "selected"; } ?><?php echo ' value="gear">Gear</option>
		<option '; ?><?php if($icon_icon == "gears") { echo "selected"; } ?><?php echo ' value="gears">Gears</option>
		<option '; ?><?php if($icon_icon == "gift") { echo "selected"; } ?><?php echo ' value="gift">Gift</option>
		<option '; ?><?php if($icon_icon == "git") { echo "selected"; } ?><?php echo ' value="git">Git</option>
		<option '; ?><?php if($icon_icon == "github") { echo "selected"; } ?><?php echo ' value="github">Github</option>
		<option '; ?><?php if($icon_icon == "github-alt") { echo "selected"; } ?><?php echo ' value="github-alt">Github-Alt</option>
		<option '; ?><?php if($icon_icon == "github-square") { echo "selected"; } ?><?php echo ' value="github-square">Github-Square</option>
		<option '; ?><?php if($icon_icon == "git-square") { echo "selected"; } ?><?php echo ' value="git-square">Git-Square</option>
		<option '; ?><?php if($icon_icon == "gittip") { echo "selected"; } ?><?php echo ' value="gittip">Gittip</option>
		<option '; ?><?php if($icon_icon == "glass") { echo "selected"; } ?><?php echo ' value="glass">Glass</option>
		<option '; ?><?php if($icon_icon == "globe") { echo "selected"; } ?><?php echo ' value="globe">Globe</option>
		<option '; ?><?php if($icon_icon == "google") { echo "selected"; } ?><?php echo ' value="google">Google</option>
		<option '; ?><?php if($icon_icon == "google-plus") { echo "selected"; } ?><?php echo ' value="google-plus">Google-Plus</option>
		<option '; ?><?php if($icon_icon == "google-plus-square") { echo "selected"; } ?><?php echo ' value="google-plus-square">Google-Plus-Square</option>
		<option '; ?><?php if($icon_icon == "google-wallet") { echo "selected"; } ?><?php echo ' value="google-wallet">Google-Wallet</option>
		<option '; ?><?php if($icon_icon == "graduation-cap") { echo "selected"; } ?><?php echo ' value="graduation-cap">Graduation-Cap</option>
		<option '; ?><?php if($icon_icon == "group") { echo "selected"; } ?><?php echo ' value="group">Group</option>
		<option '; ?><?php if($icon_icon == "hacker-news") { echo "selected"; } ?><?php echo ' value="hacker-news">Hacker-News</option>
		<option '; ?><?php if($icon_icon == "hand-o-down") { echo "selected"; } ?><?php echo ' value="hand-o-down">Hand-O-Down</option>
		<option '; ?><?php if($icon_icon == "hand-o-left") { echo "selected"; } ?><?php echo ' value="hand-o-left">Hand-O-Left</option>
		<option '; ?><?php if($icon_icon == "hand-o-right") { echo "selected"; } ?><?php echo ' value="hand-o-right">Hand-O-Right</option>
		<option '; ?><?php if($icon_icon == "hand-o-up") { echo "selected"; } ?><?php echo ' value="hand-o-up">Hand-O-Up</option>
		<option '; ?><?php if($icon_icon == "hdd-o") { echo "selected"; } ?><?php echo ' value="hdd-o">Hdd-O</option>
		<option '; ?><?php if($icon_icon == "header") { echo "selected"; } ?><?php echo ' value="header">Header</option>
		<option '; ?><?php if($icon_icon == "headphones") { echo "selected"; } ?><?php echo ' value="headphones">Headphones</option>
		<option '; ?><?php if($icon_icon == "heart") { echo "selected"; } ?><?php echo ' value="heart">Heart</option>
		<option '; ?><?php if($icon_icon == "heart-o") { echo "selected"; } ?><?php echo ' value="heart-o">Heart-O</option>
		<option '; ?><?php if($icon_icon == "history") { echo "selected"; } ?><?php echo ' value="history">History</option>
		<option '; ?><?php if($icon_icon == "home") { echo "selected"; } ?><?php echo ' value="home">Home</option>
		<option '; ?><?php if($icon_icon == "hospital-o") { echo "selected"; } ?><?php echo ' value="hospital-o">Hospital-O</option>
		<option '; ?><?php if($icon_icon == "h-square") { echo "selected"; } ?><?php echo ' value="h-square">H-Square</option>
		<option '; ?><?php if($icon_icon == "html5") { echo "selected"; } ?><?php echo ' value="html5">Html5</option>
		<option '; ?><?php if($icon_icon == "ils") { echo "selected"; } ?><?php echo ' value="ils">Ils</option>
		<option '; ?><?php if($icon_icon == "image") { echo "selected"; } ?><?php echo ' value="image">Image</option>
		<option '; ?><?php if($icon_icon == "inbox") { echo "selected"; } ?><?php echo ' value="inbox">Inbox</option>
		<option '; ?><?php if($icon_icon == "indent") { echo "selected"; } ?><?php echo ' value="indent">Indent</option>
		<option '; ?><?php if($icon_icon == "info") { echo "selected"; } ?><?php echo ' value="info">Info</option>
		<option '; ?><?php if($icon_icon == "info-circle") { echo "selected"; } ?><?php echo ' value="info-circle">Info-Circle</option>
		<option '; ?><?php if($icon_icon == "inr") { echo "selected"; } ?><?php echo ' value="inr">Inr</option>
		<option '; ?><?php if($icon_icon == "instagram") { echo "selected"; } ?><?php echo ' value="instagram">Instagram</option>
		<option '; ?><?php if($icon_icon == "institution") { echo "selected"; } ?><?php echo ' value="institution">Institution</option>
		<option '; ?><?php if($icon_icon == "ioxhost") { echo "selected"; } ?><?php echo ' value="ioxhost">Ioxhost</option>
		<option '; ?><?php if($icon_icon == "italic") { echo "selected"; } ?><?php echo ' value="italic">Italic</option>
		<option '; ?><?php if($icon_icon == "joomla") { echo "selected"; } ?><?php echo ' value="joomla">Joomla</option>
		<option '; ?><?php if($icon_icon == "jpy") { echo "selected"; } ?><?php echo ' value="jpy">Jpy</option>
		<option '; ?><?php if($icon_icon == "jsfiddle") { echo "selected"; } ?><?php echo ' value="jsfiddle">Jsfiddle</option>
		<option '; ?><?php if($icon_icon == "key") { echo "selected"; } ?><?php echo ' value="key">Key</option>
		<option '; ?><?php if($icon_icon == "keyboard-o") { echo "selected"; } ?><?php echo ' value="keyboard-o">Keyboard-O</option>
		<option '; ?><?php if($icon_icon == "krw") { echo "selected"; } ?><?php echo ' value="krw">Krw</option>
		<option '; ?><?php if($icon_icon == "language") { echo "selected"; } ?><?php echo ' value="language">Language</option>
		<option '; ?><?php if($icon_icon == "laptop") { echo "selected"; } ?><?php echo ' value="laptop">Laptop</option>
		<option '; ?><?php if($icon_icon == "lastfm") { echo "selected"; } ?><?php echo ' value="lastfm">Lastfm</option>
		<option '; ?><?php if($icon_icon == "lastfm-square") { echo "selected"; } ?><?php echo ' value="lastfm-square">Lastfm-Square</option>
		<option '; ?><?php if($icon_icon == "leaf") { echo "selected"; } ?><?php echo ' value="leaf">Leaf</option>
		<option '; ?><?php if($icon_icon == "legal") { echo "selected"; } ?><?php echo ' value="legal">Legal</option>
		<option '; ?><?php if($icon_icon == "lemon-o") { echo "selected"; } ?><?php echo ' value="lemon-o">Lemon-O</option>
		<option '; ?><?php if($icon_icon == "level-down") { echo "selected"; } ?><?php echo ' value="level-down">Level-Down</option>
		<option '; ?><?php if($icon_icon == "level-up") { echo "selected"; } ?><?php echo ' value="level-up">Level-Up</option>
		<option '; ?><?php if($icon_icon == "life-bouy") { echo "selected"; } ?><?php echo ' value="life-bouy">Life-Bouy</option>
		<option '; ?><?php if($icon_icon == "life-buoy") { echo "selected"; } ?><?php echo ' value="life-buoy">Life-Buoy</option>
		<option '; ?><?php if($icon_icon == "life-ring") { echo "selected"; } ?><?php echo ' value="life-ring">Life-Ring</option>
		<option '; ?><?php if($icon_icon == "life-saver") { echo "selected"; } ?><?php echo ' value="life-saver">Life-Saver</option>
		<option '; ?><?php if($icon_icon == "lightbulb-o") { echo "selected"; } ?><?php echo ' value="lightbulb-o">Lightbulb-O</option>
		<option '; ?><?php if($icon_icon == "line-chart") { echo "selected"; } ?><?php echo ' value="line-chart">Line-Chart</option>
		<option '; ?><?php if($icon_icon == "link") { echo "selected"; } ?><?php echo ' value="link">Link</option>
		<option '; ?><?php if($icon_icon == "linkedin") { echo "selected"; } ?><?php echo ' value="linkedin">Linkedin</option>
		<option '; ?><?php if($icon_icon == "linkedin-square") { echo "selected"; } ?><?php echo ' value="linkedin-square">Linkedin-Square</option>
		<option '; ?><?php if($icon_icon == "linux") { echo "selected"; } ?><?php echo ' value="linux">Linux</option>
		<option '; ?><?php if($icon_icon == "list") { echo "selected"; } ?><?php echo ' value="list">List</option>
		<option '; ?><?php if($icon_icon == "list-alt") { echo "selected"; } ?><?php echo ' value="list-alt">List-Alt</option>
		<option '; ?><?php if($icon_icon == "list-ol") { echo "selected"; } ?><?php echo ' value="list-ol">List-Ol</option>
		<option '; ?><?php if($icon_icon == "list-ul") { echo "selected"; } ?><?php echo ' value="list-ul">List-Ul</option>
		<option '; ?><?php if($icon_icon == "location-arrow") { echo "selected"; } ?><?php echo ' value="location-arrow">Location-Arrow</option>
		<option '; ?><?php if($icon_icon == "lock") { echo "selected"; } ?><?php echo ' value="lock">Lock</option>
		<option '; ?><?php if($icon_icon == "long-arrow-down") { echo "selected"; } ?><?php echo ' value="long-arrow-down">Long-Arrow-Down</option>
		<option '; ?><?php if($icon_icon == "long-arrow-left") { echo "selected"; } ?><?php echo ' value="long-arrow-left">Long-Arrow-Left</option>
		<option '; ?><?php if($icon_icon == "long-arrow-right") { echo "selected"; } ?><?php echo ' value="long-arrow-right">Long-Arrow-Right</option>
		<option '; ?><?php if($icon_icon == "long-arrow-up") { echo "selected"; } ?><?php echo ' value="long-arrow-up">Long-Arrow-Up</option>
		<option '; ?><?php if($icon_icon == "magic") { echo "selected"; } ?><?php echo ' value="magic">Magic</option>
		<option '; ?><?php if($icon_icon == "magnet") { echo "selected"; } ?><?php echo ' value="magnet">Magnet</option>
		<option '; ?><?php if($icon_icon == "mail-forward") { echo "selected"; } ?><?php echo ' value="mail-forward">Mail-Forward</option>
		<option '; ?><?php if($icon_icon == "mail-reply") { echo "selected"; } ?><?php echo ' value="mail-reply">Mail-Reply</option>
		<option '; ?><?php if($icon_icon == "mail-reply-all") { echo "selected"; } ?><?php echo ' value="mail-reply-all">Mail-Reply-All</option>
		<option '; ?><?php if($icon_icon == "male") { echo "selected"; } ?><?php echo ' value="male">Male</option>
		<option '; ?><?php if($icon_icon == "map-marker") { echo "selected"; } ?><?php echo ' value="map-marker">Map-Marker</option>
		<option '; ?><?php if($icon_icon == "maxcdn") { echo "selected"; } ?><?php echo ' value="maxcdn">Maxcdn</option>
		<option '; ?><?php if($icon_icon == "meanpath") { echo "selected"; } ?><?php echo ' value="meanpath">Meanpath</option>
		<option '; ?><?php if($icon_icon == "medkit") { echo "selected"; } ?><?php echo ' value="medkit">Medkit</option>
		<option '; ?><?php if($icon_icon == "meh-o") { echo "selected"; } ?><?php echo ' value="meh-o">Meh-O</option>
		<option '; ?><?php if($icon_icon == "microphone") { echo "selected"; } ?><?php echo ' value="microphone">Microphone</option>
		<option '; ?><?php if($icon_icon == "microphone-slash") { echo "selected"; } ?><?php echo ' value="microphone-slash">Microphone-Slash</option>
		<option '; ?><?php if($icon_icon == "minus") { echo "selected"; } ?><?php echo ' value="minus">Minus</option>
		<option '; ?><?php if($icon_icon == "minus-circle") { echo "selected"; } ?><?php echo ' value="minus-circle">Minus-Circle</option>
		<option '; ?><?php if($icon_icon == "minus-square") { echo "selected"; } ?><?php echo ' value="minus-square">Minus-Square</option>
		<option '; ?><?php if($icon_icon == "minus-square-o") { echo "selected"; } ?><?php echo ' value="minus-square-o">Minus-Square-O</option>
		<option '; ?><?php if($icon_icon == "mobile") { echo "selected"; } ?><?php echo ' value="mobile">Mobile</option>
		<option '; ?><?php if($icon_icon == "mobile-phone") { echo "selected"; } ?><?php echo ' value="mobile-phone">Mobile-Phone</option>
		<option '; ?><?php if($icon_icon == "money") { echo "selected"; } ?><?php echo ' value="money">Money</option>
		<option '; ?><?php if($icon_icon == "moon-o") { echo "selected"; } ?><?php echo ' value="moon-o">Moon-O</option>
		<option '; ?><?php if($icon_icon == "mortar-board") { echo "selected"; } ?><?php echo ' value="mortar-board">Mortar-Board</option>
		<option '; ?><?php if($icon_icon == "music") { echo "selected"; } ?><?php echo ' value="music">Music</option>
		<option '; ?><?php if($icon_icon == "navicon") { echo "selected"; } ?><?php echo ' value="navicon">Navicon</option>
		<option '; ?><?php if($icon_icon == "newspaper-o") { echo "selected"; } ?><?php echo ' value="newspaper-o">Newspaper-O</option>
		<option '; ?><?php if($icon_icon == "openid") { echo "selected"; } ?><?php echo ' value="openid">Openid</option>
		<option '; ?><?php if($icon_icon == "outdent") { echo "selected"; } ?><?php echo ' value="outdent">Outdent</option>
		<option '; ?><?php if($icon_icon == "pagelines") { echo "selected"; } ?><?php echo ' value="pagelines">Pagelines</option>
		<option '; ?><?php if($icon_icon == "paint-brush") { echo "selected"; } ?><?php echo ' value="paint-brush">Paint-Brush</option>
		<option '; ?><?php if($icon_icon == "paperclip") { echo "selected"; } ?><?php echo ' value="paperclip">Paperclip</option>
		<option '; ?><?php if($icon_icon == "paper-plane") { echo "selected"; } ?><?php echo ' value="paper-plane">Paper-Plane</option>
		<option '; ?><?php if($icon_icon == "paper-plane-o") { echo "selected"; } ?><?php echo ' value="paper-plane-o">Paper-Plane-O</option>
		<option '; ?><?php if($icon_icon == "paragraph") { echo "selected"; } ?><?php echo ' value="paragraph">Paragraph</option>
		<option '; ?><?php if($icon_icon == "paste") { echo "selected"; } ?><?php echo ' value="paste">Paste</option>
		<option '; ?><?php if($icon_icon == "pause") { echo "selected"; } ?><?php echo ' value="pause">Pause</option>
		<option '; ?><?php if($icon_icon == "paw") { echo "selected"; } ?><?php echo ' value="paw">Paw</option>
		<option '; ?><?php if($icon_icon == "paypal") { echo "selected"; } ?><?php echo ' value="paypal">Paypal</option>
		<option '; ?><?php if($icon_icon == "pencil") { echo "selected"; } ?><?php echo ' value="pencil">Pencil</option>
		<option '; ?><?php if($icon_icon == "pencil-square") { echo "selected"; } ?><?php echo ' value="pencil-square">Pencil-Square</option>
		<option '; ?><?php if($icon_icon == "pencil-square-o") { echo "selected"; } ?><?php echo ' value="pencil-square-o">Pencil-Square-O</option>
		<option '; ?><?php if($icon_icon == "phone") { echo "selected"; } ?><?php echo ' value="phone">Phone</option>
		<option '; ?><?php if($icon_icon == "phone-square") { echo "selected"; } ?><?php echo ' value="phone-square">Phone-Square</option>
		<option '; ?><?php if($icon_icon == "photo") { echo "selected"; } ?><?php echo ' value="photo">Photo</option>
		<option '; ?><?php if($icon_icon == "picture-o") { echo "selected"; } ?><?php echo ' value="picture-o">Picture-O</option>
		<option '; ?><?php if($icon_icon == "pie-chart") { echo "selected"; } ?><?php echo ' value="pie-chart">Pie-Chart</option>
		<option '; ?><?php if($icon_icon == "pied-piper") { echo "selected"; } ?><?php echo ' value="pied-piper">Pied-Piper</option>
		<option '; ?><?php if($icon_icon == "pied-piper-alt") { echo "selected"; } ?><?php echo ' value="pied-piper-alt">Pied-Piper-Alt</option>
		<option '; ?><?php if($icon_icon == "pinterest") { echo "selected"; } ?><?php echo ' value="pinterest">Pinterest</option>
		<option '; ?><?php if($icon_icon == "pinterest-square") { echo "selected"; } ?><?php echo ' value="pinterest-square">Pinterest-Square</option>
		<option '; ?><?php if($icon_icon == "plane") { echo "selected"; } ?><?php echo ' value="plane">Plane</option>
		<option '; ?><?php if($icon_icon == "play") { echo "selected"; } ?><?php echo ' value="play">Play</option>
		<option '; ?><?php if($icon_icon == "play-circle") { echo "selected"; } ?><?php echo ' value="play-circle">Play-Circle</option>
		<option '; ?><?php if($icon_icon == "play-circle-o") { echo "selected"; } ?><?php echo ' value="play-circle-o">Play-Circle-O</option>
		<option '; ?><?php if($icon_icon == "plug") { echo "selected"; } ?><?php echo ' value="plug">Plug</option>
		<option '; ?><?php if($icon_icon == "plus") { echo "selected"; } ?><?php echo ' value="plus">Plus</option>
		<option '; ?><?php if($icon_icon == "plus-circle") { echo "selected"; } ?><?php echo ' value="plus-circle">Plus-Circle</option>
		<option '; ?><?php if($icon_icon == "plus-square") { echo "selected"; } ?><?php echo ' value="plus-square">Plus-Square</option>
		<option '; ?><?php if($icon_icon == "plus-square-o") { echo "selected"; } ?><?php echo ' value="plus-square-o">Plus-Square-O</option>
		<option '; ?><?php if($icon_icon == "power-off") { echo "selected"; } ?><?php echo ' value="power-off">Power-Off</option>
		<option '; ?><?php if($icon_icon == "print") { echo "selected"; } ?><?php echo ' value="print">Print</option>
		<option '; ?><?php if($icon_icon == "puzzle-piece") { echo "selected"; } ?><?php echo ' value="puzzle-piece">Puzzle-Piece</option>
		<option '; ?><?php if($icon_icon == "qq") { echo "selected"; } ?><?php echo ' value="qq">Qq</option>
		<option '; ?><?php if($icon_icon == "qrcode") { echo "selected"; } ?><?php echo ' value="qrcode">Qrcode</option>
		<option '; ?><?php if($icon_icon == "question") { echo "selected"; } ?><?php echo ' value="question">Question</option>
		<option '; ?><?php if($icon_icon == "question-circle") { echo "selected"; } ?><?php echo ' value="question-circle">Question-Circle</option>
		<option '; ?><?php if($icon_icon == "quote-left") { echo "selected"; } ?><?php echo ' value="quote-left">Quote-Left</option>
		<option '; ?><?php if($icon_icon == "quote-right") { echo "selected"; } ?><?php echo ' value="quote-right">Quote-Right</option>
		<option '; ?><?php if($icon_icon == "ra") { echo "selected"; } ?><?php echo ' value="ra">Ra</option>
		<option '; ?><?php if($icon_icon == "random") { echo "selected"; } ?><?php echo ' value="random">Random</option>
		<option '; ?><?php if($icon_icon == "rebel") { echo "selected"; } ?><?php echo ' value="rebel">Rebel</option>
		<option '; ?><?php if($icon_icon == "recycle") { echo "selected"; } ?><?php echo ' value="recycle">Recycle</option>
		<option '; ?><?php if($icon_icon == "reddit") { echo "selected"; } ?><?php echo ' value="reddit">Reddit</option>
		<option '; ?><?php if($icon_icon == "reddit-square") { echo "selected"; } ?><?php echo ' value="reddit-square">Reddit-Square</option>
		<option '; ?><?php if($icon_icon == "refresh") { echo "selected"; } ?><?php echo ' value="refresh">Refresh</option>
		<option '; ?><?php if($icon_icon == "remove") { echo "selected"; } ?><?php echo ' value="remove">Remove</option>
		<option '; ?><?php if($icon_icon == "renren") { echo "selected"; } ?><?php echo ' value="renren">Renren</option>
		<option '; ?><?php if($icon_icon == "reorder") { echo "selected"; } ?><?php echo ' value="reorder">Reorder</option>
		<option '; ?><?php if($icon_icon == "repeat") { echo "selected"; } ?><?php echo ' value="repeat">Repeat</option>
		<option '; ?><?php if($icon_icon == "reply") { echo "selected"; } ?><?php echo ' value="reply">Reply</option>
		<option '; ?><?php if($icon_icon == "reply-all") { echo "selected"; } ?><?php echo ' value="reply-all">Reply-All</option>
		<option '; ?><?php if($icon_icon == "retweet") { echo "selected"; } ?><?php echo ' value="retweet">Retweet</option>
		<option '; ?><?php if($icon_icon == "rmb") { echo "selected"; } ?><?php echo ' value="rmb">Rmb</option>
		<option '; ?><?php if($icon_icon == "road") { echo "selected"; } ?><?php echo ' value="road">Road</option>
		<option '; ?><?php if($icon_icon == "rocket") { echo "selected"; } ?><?php echo ' value="rocket">Rocket</option>
		<option '; ?><?php if($icon_icon == "rotate-left") { echo "selected"; } ?><?php echo ' value="rotate-left">Rotate-Left</option>
		<option '; ?><?php if($icon_icon == "rotate-right") { echo "selected"; } ?><?php echo ' value="rotate-right">Rotate-Right</option>
		<option '; ?><?php if($icon_icon == "rouble") { echo "selected"; } ?><?php echo ' value="rouble">Rouble</option>
		<option '; ?><?php if($icon_icon == "rss") { echo "selected"; } ?><?php echo ' value="rss">Rss</option>
		<option '; ?><?php if($icon_icon == "rss-square") { echo "selected"; } ?><?php echo ' value="rss-square">Rss-Square</option>
		<option '; ?><?php if($icon_icon == "rub") { echo "selected"; } ?><?php echo ' value="rub">Rub</option>
		<option '; ?><?php if($icon_icon == "ruble") { echo "selected"; } ?><?php echo ' value="ruble">Ruble</option>
		<option '; ?><?php if($icon_icon == "rupee") { echo "selected"; } ?><?php echo ' value="rupee">Rupee</option>
		<option '; ?><?php if($icon_icon == "save") { echo "selected"; } ?><?php echo ' value="save">Save</option>
		<option '; ?><?php if($icon_icon == "scissors") { echo "selected"; } ?><?php echo ' value="scissors">Scissors</option>
		<option '; ?><?php if($icon_icon == "search") { echo "selected"; } ?><?php echo ' value="search">Search</option>
		<option '; ?><?php if($icon_icon == "search-minus") { echo "selected"; } ?><?php echo ' value="search-minus">Search-Minus</option>
		<option '; ?><?php if($icon_icon == "search-plus") { echo "selected"; } ?><?php echo ' value="search-plus">Search-Plus</option>
		<option '; ?><?php if($icon_icon == "send") { echo "selected"; } ?><?php echo ' value="send">Send</option>
		<option '; ?><?php if($icon_icon == "send-o") { echo "selected"; } ?><?php echo ' value="send-o">Send-O</option>
		<option '; ?><?php if($icon_icon == "share") { echo "selected"; } ?><?php echo ' value="share">Share</option>
		<option '; ?><?php if($icon_icon == "share-alt") { echo "selected"; } ?><?php echo ' value="share-alt">Share-Alt</option>
		<option '; ?><?php if($icon_icon == "share-alt-square") { echo "selected"; } ?><?php echo ' value="share-alt-square">Share-Alt-Square</option>
		<option '; ?><?php if($icon_icon == "share-square") { echo "selected"; } ?><?php echo ' value="share-square">Share-Square</option>
		<option '; ?><?php if($icon_icon == "share-square-o") { echo "selected"; } ?><?php echo ' value="share-square-o">Share-Square-O</option>
		<option '; ?><?php if($icon_icon == "shekel") { echo "selected"; } ?><?php echo ' value="shekel">Shekel</option>
		<option '; ?><?php if($icon_icon == "sheqel") { echo "selected"; } ?><?php echo ' value="sheqel">Sheqel</option>
		<option '; ?><?php if($icon_icon == "shield") { echo "selected"; } ?><?php echo ' value="shield">Shield</option>
		<option '; ?><?php if($icon_icon == "shopping-cart") { echo "selected"; } ?><?php echo ' value="shopping-cart">Shopping-Cart</option>
		<option '; ?><?php if($icon_icon == "signal") { echo "selected"; } ?><?php echo ' value="signal">Signal</option>
		<option '; ?><?php if($icon_icon == "sign-in") { echo "selected"; } ?><?php echo ' value="sign-in">Sign-In</option>
		<option '; ?><?php if($icon_icon == "sign-out") { echo "selected"; } ?><?php echo ' value="sign-out">Sign-Out</option>
		<option '; ?><?php if($icon_icon == "sitemap") { echo "selected"; } ?><?php echo ' value="sitemap">Sitemap</option>
		<option '; ?><?php if($icon_icon == "skype") { echo "selected"; } ?><?php echo ' value="skype">Skype</option>
		<option '; ?><?php if($icon_icon == "slack") { echo "selected"; } ?><?php echo ' value="slack">Slack</option>
		<option '; ?><?php if($icon_icon == "sliders") { echo "selected"; } ?><?php echo ' value="sliders">Sliders</option>
		<option '; ?><?php if($icon_icon == "slideshare") { echo "selected"; } ?><?php echo ' value="slideshare">Slideshare</option>
		<option '; ?><?php if($icon_icon == "smile-o") { echo "selected"; } ?><?php echo ' value="smile-o">Smile-O</option>
		<option '; ?><?php if($icon_icon == "soccer-ball-o") { echo "selected"; } ?><?php echo ' value="soccer-ball-o">Soccer-Ball-O</option>
		<option '; ?><?php if($icon_icon == "sort") { echo "selected"; } ?><?php echo ' value="sort">Sort</option>
		<option '; ?><?php if($icon_icon == "sort-alpha-asc") { echo "selected"; } ?><?php echo ' value="sort-alpha-asc">Sort-Alpha-Asc</option>
		<option '; ?><?php if($icon_icon == "sort-alpha-desc") { echo "selected"; } ?><?php echo ' value="sort-alpha-desc">Sort-Alpha-Desc</option>
		<option '; ?><?php if($icon_icon == "sort-amount-asc") { echo "selected"; } ?><?php echo ' value="sort-amount-asc">Sort-Amount-Asc</option>
		<option '; ?><?php if($icon_icon == "sort-amount-desc") { echo "selected"; } ?><?php echo ' value="sort-amount-desc">Sort-Amount-Desc</option>
		<option '; ?><?php if($icon_icon == "sort-asc") { echo "selected"; } ?><?php echo ' value="sort-asc">Sort-Asc</option>
		<option '; ?><?php if($icon_icon == "sort-desc") { echo "selected"; } ?><?php echo ' value="sort-desc">Sort-Desc</option>
		<option '; ?><?php if($icon_icon == "sort-down") { echo "selected"; } ?><?php echo ' value="sort-down">Sort-Down</option>
		<option '; ?><?php if($icon_icon == "sort-numeric-asc") { echo "selected"; } ?><?php echo ' value="sort-numeric-asc">Sort-Numeric-Asc</option>
		<option '; ?><?php if($icon_icon == "sort-numeric-desc") { echo "selected"; } ?><?php echo ' value="sort-numeric-desc">Sort-Numeric-Desc</option>
		<option '; ?><?php if($icon_icon == "sort-up") { echo "selected"; } ?><?php echo ' value="sort-up">Sort-Up</option>
		<option '; ?><?php if($icon_icon == "soundcloud") { echo "selected"; } ?><?php echo ' value="soundcloud">Soundcloud</option>
		<option '; ?><?php if($icon_icon == "space-shuttle") { echo "selected"; } ?><?php echo ' value="space-shuttle">Space-Shuttle</option>
		<option '; ?><?php if($icon_icon == "spinner") { echo "selected"; } ?><?php echo ' value="spinner">Spinner</option>
		<option '; ?><?php if($icon_icon == "spoon") { echo "selected"; } ?><?php echo ' value="spoon">Spoon</option>
		<option '; ?><?php if($icon_icon == "spotify") { echo "selected"; } ?><?php echo ' value="spotify">Spotify</option>
		<option '; ?><?php if($icon_icon == "square") { echo "selected"; } ?><?php echo ' value="square">Square</option>
		<option '; ?><?php if($icon_icon == "square-o") { echo "selected"; } ?><?php echo ' value="square-o">Square-O</option>
		<option '; ?><?php if($icon_icon == "stack-exchange") { echo "selected"; } ?><?php echo ' value="stack-exchange">Stack-Exchange</option>
		<option '; ?><?php if($icon_icon == "stack-overflow") { echo "selected"; } ?><?php echo ' value="stack-overflow">Stack-Overflow</option>
		<option '; ?><?php if($icon_icon == "star") { echo "selected"; } ?><?php echo ' value="star">Star</option>
		<option '; ?><?php if($icon_icon == "star-half") { echo "selected"; } ?><?php echo ' value="star-half">Star-Half</option>
		<option '; ?><?php if($icon_icon == "star-half-empty") { echo "selected"; } ?><?php echo ' value="star-half-empty">Star-Half-Empty</option>
		<option '; ?><?php if($icon_icon == "star-half-full") { echo "selected"; } ?><?php echo ' value="star-half-full">Star-Half-Full</option>
		<option '; ?><?php if($icon_icon == "star-half-o") { echo "selected"; } ?><?php echo ' value="star-half-o">Star-Half-O</option>
		<option '; ?><?php if($icon_icon == "star-o") { echo "selected"; } ?><?php echo ' value="star-o">Star-O</option>
		<option '; ?><?php if($icon_icon == "steam") { echo "selected"; } ?><?php echo ' value="steam">Steam</option>
		<option '; ?><?php if($icon_icon == "steam-square") { echo "selected"; } ?><?php echo ' value="steam-square">Steam-Square</option>
		<option '; ?><?php if($icon_icon == "step-backward") { echo "selected"; } ?><?php echo ' value="step-backward">Step-Backward</option>
		<option '; ?><?php if($icon_icon == "step-forward") { echo "selected"; } ?><?php echo ' value="step-forward">Step-Forward</option>
		<option '; ?><?php if($icon_icon == "stethoscope") { echo "selected"; } ?><?php echo ' value="stethoscope">Stethoscope</option>
		<option '; ?><?php if($icon_icon == "stop") { echo "selected"; } ?><?php echo ' value="stop">Stop</option>
		<option '; ?><?php if($icon_icon == "strikethrough") { echo "selected"; } ?><?php echo ' value="strikethrough">Strikethrough</option>
		<option '; ?><?php if($icon_icon == "stumbleupon") { echo "selected"; } ?><?php echo ' value="stumbleupon">Stumbleupon</option>
		<option '; ?><?php if($icon_icon == "stumbleupon-circle") { echo "selected"; } ?><?php echo ' value="stumbleupon-circle">Stumbleupon-Circle</option>
		<option '; ?><?php if($icon_icon == "subscript") { echo "selected"; } ?><?php echo ' value="subscript">Subscript</option>
		<option '; ?><?php if($icon_icon == "suitcase") { echo "selected"; } ?><?php echo ' value="suitcase">Suitcase</option>
		<option '; ?><?php if($icon_icon == "sun-o") { echo "selected"; } ?><?php echo ' value="sun-o">Sun-O</option>
		<option '; ?><?php if($icon_icon == "superscript") { echo "selected"; } ?><?php echo ' value="superscript">Superscript</option>
		<option '; ?><?php if($icon_icon == "support") { echo "selected"; } ?><?php echo ' value="support">Support</option>
		<option '; ?><?php if($icon_icon == "table") { echo "selected"; } ?><?php echo ' value="table">Table</option>
		<option '; ?><?php if($icon_icon == "tablet") { echo "selected"; } ?><?php echo ' value="tablet">Tablet</option>
		<option '; ?><?php if($icon_icon == "tachometer") { echo "selected"; } ?><?php echo ' value="tachometer">Tachometer</option>
		<option '; ?><?php if($icon_icon == "tag") { echo "selected"; } ?><?php echo ' value="tag">Tag</option>
		<option '; ?><?php if($icon_icon == "tags") { echo "selected"; } ?><?php echo ' value="tags">Tags</option>
		<option '; ?><?php if($icon_icon == "tasks") { echo "selected"; } ?><?php echo ' value="tasks">Tasks</option>
		<option '; ?><?php if($icon_icon == "taxi") { echo "selected"; } ?><?php echo ' value="taxi">Taxi</option>
		<option '; ?><?php if($icon_icon == "tencent-weibo") { echo "selected"; } ?><?php echo ' value="tencent-weibo">Tencent-Weibo</option>
		<option '; ?><?php if($icon_icon == "terminal") { echo "selected"; } ?><?php echo ' value="terminal">Terminal</option>
		<option '; ?><?php if($icon_icon == "text-height") { echo "selected"; } ?><?php echo ' value="text-height">Text-Height</option>
		<option '; ?><?php if($icon_icon == "text-width") { echo "selected"; } ?><?php echo ' value="text-width">Text-Width</option>
		<option '; ?><?php if($icon_icon == "th") { echo "selected"; } ?><?php echo ' value="th">Th</option>
		<option '; ?><?php if($icon_icon == "th-large") { echo "selected"; } ?><?php echo ' value="th-large">Th-Large</option>
		<option '; ?><?php if($icon_icon == "th-list") { echo "selected"; } ?><?php echo ' value="th-list">Th-List</option>
		<option '; ?><?php if($icon_icon == "thumbs-down") { echo "selected"; } ?><?php echo ' value="thumbs-down">Thumbs-Down</option>
		<option '; ?><?php if($icon_icon == "thumbs-o-down") { echo "selected"; } ?><?php echo ' value="thumbs-o-down">Thumbs-O-Down</option>
		<option '; ?><?php if($icon_icon == "thumbs-o-up") { echo "selected"; } ?><?php echo ' value="thumbs-o-up">Thumbs-O-Up</option>
		<option '; ?><?php if($icon_icon == "thumbs-up") { echo "selected"; } ?><?php echo ' value="thumbs-up">Thumbs-Up</option>
		<option '; ?><?php if($icon_icon == "thumb-tack") { echo "selected"; } ?><?php echo ' value="thumb-tack">Thumb-Tack</option>
		<option '; ?><?php if($icon_icon == "ticket") { echo "selected"; } ?><?php echo ' value="ticket">Ticket</option>
		<option '; ?><?php if($icon_icon == "times") { echo "selected"; } ?><?php echo ' value="times">Times</option>
		<option '; ?><?php if($icon_icon == "times-circle") { echo "selected"; } ?><?php echo ' value="times-circle">Times-Circle</option>
		<option '; ?><?php if($icon_icon == "times-circle-o") { echo "selected"; } ?><?php echo ' value="times-circle-o">Times-Circle-O</option>
		<option '; ?><?php if($icon_icon == "tint") { echo "selected"; } ?><?php echo ' value="tint">Tint</option>
		<option '; ?><?php if($icon_icon == "toggle-down") { echo "selected"; } ?><?php echo ' value="toggle-down">Toggle-Down</option>
		<option '; ?><?php if($icon_icon == "toggle-left") { echo "selected"; } ?><?php echo ' value="toggle-left">Toggle-Left</option>
		<option '; ?><?php if($icon_icon == "toggle-off") { echo "selected"; } ?><?php echo ' value="toggle-off">Toggle-Off</option>
		<option '; ?><?php if($icon_icon == "toggle-on") { echo "selected"; } ?><?php echo ' value="toggle-on">Toggle-On</option>
		<option '; ?><?php if($icon_icon == "toggle-right") { echo "selected"; } ?><?php echo ' value="toggle-right">Toggle-Right</option>
		<option '; ?><?php if($icon_icon == "toggle-up") { echo "selected"; } ?><?php echo ' value="toggle-up">Toggle-Up</option>
		<option '; ?><?php if($icon_icon == "trash") { echo "selected"; } ?><?php echo ' value="trash">Trash</option>
		<option '; ?><?php if($icon_icon == "trash-o") { echo "selected"; } ?><?php echo ' value="trash-o">Trash-O</option>
		<option '; ?><?php if($icon_icon == "tree") { echo "selected"; } ?><?php echo ' value="tree">Tree</option>
		<option '; ?><?php if($icon_icon == "trello") { echo "selected"; } ?><?php echo ' value="trello">Trello</option>
		<option '; ?><?php if($icon_icon == "trophy") { echo "selected"; } ?><?php echo ' value="trophy">Trophy</option>
		<option '; ?><?php if($icon_icon == "truck") { echo "selected"; } ?><?php echo ' value="truck">Truck</option>
		<option '; ?><?php if($icon_icon == "try") { echo "selected"; } ?><?php echo ' value="try">Try</option>
		<option '; ?><?php if($icon_icon == "tty") { echo "selected"; } ?><?php echo ' value="tty">Tty</option>
		<option '; ?><?php if($icon_icon == "tumblr") { echo "selected"; } ?><?php echo ' value="tumblr">Tumblr</option>
		<option '; ?><?php if($icon_icon == "tumblr-square") { echo "selected"; } ?><?php echo ' value="tumblr-square">Tumblr-Square</option>
		<option '; ?><?php if($icon_icon == "turkish-lira") { echo "selected"; } ?><?php echo ' value="turkish-lira">Turkish-Lira</option>
		<option '; ?><?php if($icon_icon == "twitch") { echo "selected"; } ?><?php echo ' value="twitch">Twitch</option>
		<option '; ?><?php if($icon_icon == "twitter") { echo "selected"; } ?><?php echo ' value="twitter">Twitter</option>
		<option '; ?><?php if($icon_icon == "twitter-square") { echo "selected"; } ?><?php echo ' value="twitter-square">Twitter-Square</option>
		<option '; ?><?php if($icon_icon == "umbrella") { echo "selected"; } ?><?php echo ' value="umbrella">Umbrella</option>
		<option '; ?><?php if($icon_icon == "underline") { echo "selected"; } ?><?php echo ' value="underline">Underline</option>
		<option '; ?><?php if($icon_icon == "undo") { echo "selected"; } ?><?php echo ' value="undo">Undo</option>
		<option '; ?><?php if($icon_icon == "university") { echo "selected"; } ?><?php echo ' value="university">University</option>
		<option '; ?><?php if($icon_icon == "unlink") { echo "selected"; } ?><?php echo ' value="unlink">Unlink</option>
		<option '; ?><?php if($icon_icon == "unlock") { echo "selected"; } ?><?php echo ' value="unlock">Unlock</option>
		<option '; ?><?php if($icon_icon == "unlock-alt") { echo "selected"; } ?><?php echo ' value="unlock-alt">Unlock-Alt</option>
		<option '; ?><?php if($icon_icon == "unsorted") { echo "selected"; } ?><?php echo ' value="unsorted">Unsorted</option>
		<option '; ?><?php if($icon_icon == "upload") { echo "selected"; } ?><?php echo ' value="upload">Upload</option>
		<option '; ?><?php if($icon_icon == "usd") { echo "selected"; } ?><?php echo ' value="usd">Usd</option>
		<option '; ?><?php if($icon_icon == "user") { echo "selected"; } ?><?php echo ' value="user">User</option>
		<option '; ?><?php if($icon_icon == "user-md") { echo "selected"; } ?><?php echo ' value="user-md">User-Md</option>
		<option '; ?><?php if($icon_icon == "users") { echo "selected"; } ?><?php echo ' value="users">Users</option>
		<option '; ?><?php if($icon_icon == "video-camera") { echo "selected"; } ?><?php echo ' value="video-camera">Video-Camera</option>
		<option '; ?><?php if($icon_icon == "vimeo-square") { echo "selected"; } ?><?php echo ' value="vimeo-square">Vimeo-Square</option>
		<option '; ?><?php if($icon_icon == "vine") { echo "selected"; } ?><?php echo ' value="vine">Vine</option>
		<option '; ?><?php if($icon_icon == "vk") { echo "selected"; } ?><?php echo ' value="vk">Vk</option>
		<option '; ?><?php if($icon_icon == "volume-down") { echo "selected"; } ?><?php echo ' value="volume-down">Volume-Down</option>
		<option '; ?><?php if($icon_icon == "volume-off") { echo "selected"; } ?><?php echo ' value="volume-off">Volume-Off</option>
		<option '; ?><?php if($icon_icon == "volume-up") { echo "selected"; } ?><?php echo ' value="volume-up">Volume-Up</option>
		<option '; ?><?php if($icon_icon == "warning") { echo "selected"; } ?><?php echo ' value="warning">Warning</option>
		<option '; ?><?php if($icon_icon == "wechat") { echo "selected"; } ?><?php echo ' value="wechat">Wechat</option>
		<option '; ?><?php if($icon_icon == "weibo") { echo "selected"; } ?><?php echo ' value="weibo">Weibo</option>
		<option '; ?><?php if($icon_icon == "weixin") { echo "selected"; } ?><?php echo ' value="weixin">Weixin</option>
		<option '; ?><?php if($icon_icon == "wheelchair") { echo "selected"; } ?><?php echo ' value="wheelchair">Wheelchair</option>
		<option '; ?><?php if($icon_icon == "wifi") { echo "selected"; } ?><?php echo ' value="wifi">Wifi</option>
		<option '; ?><?php if($icon_icon == "windows") { echo "selected"; } ?><?php echo ' value="windows">Windows</option>
		<option '; ?><?php if($icon_icon == "won") { echo "selected"; } ?><?php echo ' value="won">Won</option>
		<option '; ?><?php if($icon_icon == "wordpress") { echo "selected"; } ?><?php echo ' value="wordpress">Wordpress</option>
		<option '; ?><?php if($icon_icon == "wrench") { echo "selected"; } ?><?php echo ' value="wrench">Wrench</option>
		<option '; ?><?php if($icon_icon == "xing") { echo "selected"; } ?><?php echo ' value="xing">Xing</option>
		<option '; ?><?php if($icon_icon == "xing-square") { echo "selected"; } ?><?php echo ' value="xing-square">Xing-Square</option>
		<option '; ?><?php if($icon_icon == "yahoo") { echo "selected"; } ?><?php echo ' value="yahoo">Yahoo</option>
		<option '; ?><?php if($icon_icon == "yelp") { echo "selected"; } ?><?php echo ' value="yelp">Yelp</option>
		<option '; ?><?php if($icon_icon == "yen") { echo "selected"; } ?><?php echo ' value="yen">Yen</option>
		<option '; ?><?php if($icon_icon == "youtube") { echo "selected"; } ?><?php echo ' value="youtube">Youtube</option>
		<option '; ?><?php if($icon_icon == "youtube-play") { echo "selected"; } ?><?php echo ' value="youtube-play">Youtube-Play</option>
		<option '; ?><?php if($icon_icon == "youtube-square") { echo "selected"; } ?><?php echo ' value="youtube-square">Youtube-Square</option>';
}

?>